//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LongPolling.Client.NotificationServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotificationServiceReference.INotificationService")]
    public interface INotificationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/Register", ReplyAction="http://tempuri.org/INotificationService/RegisterResponse")]
        void Register(LongPolling.User client);
        
        // CODEGEN: Generating message contract since the wrapper name (GetNotifications_x0028__x0029_) of message GetNotifications_x0028__x0029_Request does not match the default value (GetNotifications)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/GetNotifications()", ReplyAction="http://tempuri.org/INotificationService/GetNotifications()Response")]
        LongPolling.Client.NotificationServiceReference.GetNotificationsResponse GetNotifications(LongPolling.Client.NotificationServiceReference.GetNotificationsRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (GetNotifications_x0028_User_x002C__x0020_TimeSpan_x0029_) of message GetNotifications_x0028_User_x002C__x0020_TimeSpan_x0029_Request does not match the default value (GetNotificationsUserTimeSpan)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/GetNotifications(User, TimeSpan)", ReplyAction="http://tempuri.org/INotificationService/GetNotifications(User, TimeSpan)Response")]
        LongPolling.Client.NotificationServiceReference.GetNotificationsUserTimeSpanResponse GetNotificationsUserTimeSpan(LongPolling.Client.NotificationServiceReference.GetNotificationsUserTimeSpanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotificationService/Unregister", ReplyAction="http://tempuri.org/INotificationService/UnregisterResponse")]
        void Unregister(LongPolling.User user);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotifications()", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNotificationsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public LongPolling.User user;
        
        public GetNotificationsRequest() {
        }
        
        public GetNotificationsRequest(LongPolling.User user) {
            this.user = user;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotifications()Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNotificationsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNotifications_x0028__x0029_Result", Namespace="http://tempuri.org/", Order=0)]
        public LongPolling.Notification[] GetNotificationsResult;
        
        public GetNotificationsResponse() {
        }
        
        public GetNotificationsResponse(LongPolling.Notification[] GetNotificationsResult) {
            this.GetNotificationsResult = GetNotificationsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotifications(User, TimeSpan)", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNotificationsUserTimeSpanRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public LongPolling.User user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public System.TimeSpan timeout;
        
        public GetNotificationsUserTimeSpanRequest() {
        }
        
        public GetNotificationsUserTimeSpanRequest(LongPolling.User user, System.TimeSpan timeout) {
            this.user = user;
            this.timeout = timeout;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetNotifications(User, TimeSpan)Response", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetNotificationsUserTimeSpanResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNotifications_x0028_User_x002C__x0020_TimeSpan_x0029_Result", Namespace="http://tempuri.org/", Order=0)]
        public LongPolling.Notification[] GetNotificationsUserTimeSpanResult;
        
        public GetNotificationsUserTimeSpanResponse() {
        }
        
        public GetNotificationsUserTimeSpanResponse(LongPolling.Notification[] GetNotificationsUserTimeSpanResult) {
            this.GetNotificationsUserTimeSpanResult = GetNotificationsUserTimeSpanResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INotificationServiceChannel : LongPolling.Client.NotificationServiceReference.INotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationServiceClient : System.ServiceModel.ClientBase<LongPolling.Client.NotificationServiceReference.INotificationService>, LongPolling.Client.NotificationServiceReference.INotificationService {
        
        public NotificationServiceClient() {
        }
        
        public NotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Register(LongPolling.User client) {
            base.Channel.Register(client);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LongPolling.Client.NotificationServiceReference.GetNotificationsResponse LongPolling.Client.NotificationServiceReference.INotificationService.GetNotifications(LongPolling.Client.NotificationServiceReference.GetNotificationsRequest request) {
            return base.Channel.GetNotifications(request);
        }
        
        public LongPolling.Notification[] GetNotifications(LongPolling.User user) {
            LongPolling.Client.NotificationServiceReference.GetNotificationsRequest inValue = new LongPolling.Client.NotificationServiceReference.GetNotificationsRequest();
            inValue.user = user;
            LongPolling.Client.NotificationServiceReference.GetNotificationsResponse retVal = ((LongPolling.Client.NotificationServiceReference.INotificationService)(this)).GetNotifications(inValue);
            return retVal.GetNotificationsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LongPolling.Client.NotificationServiceReference.GetNotificationsUserTimeSpanResponse LongPolling.Client.NotificationServiceReference.INotificationService.GetNotificationsUserTimeSpan(LongPolling.Client.NotificationServiceReference.GetNotificationsUserTimeSpanRequest request) {
            return base.Channel.GetNotificationsUserTimeSpan(request);
        }
        
        public LongPolling.Notification[] GetNotificationsUserTimeSpan(LongPolling.User user, System.TimeSpan timeout) {
            LongPolling.Client.NotificationServiceReference.GetNotificationsUserTimeSpanRequest inValue = new LongPolling.Client.NotificationServiceReference.GetNotificationsUserTimeSpanRequest();
            inValue.user = user;
            inValue.timeout = timeout;
            LongPolling.Client.NotificationServiceReference.GetNotificationsUserTimeSpanResponse retVal = ((LongPolling.Client.NotificationServiceReference.INotificationService)(this)).GetNotificationsUserTimeSpan(inValue);
            return retVal.GetNotificationsUserTimeSpanResult;
        }
        
        public void Unregister(LongPolling.User user) {
            base.Channel.Unregister(user);
        }
    }
}
